from .base_errors import AppError

class DatabaseError(AppError): ...
class DatabaseConnectionError(DatabaseError): ...
class DatabaseIntegrityError(DatabaseError): ...
class DatabaseConfigurationError(DatabaseError): ...
class MigrationError(DatabaseError): ...
