from .base_errors import AppError

class SeederError(AppError): ...
class SeederNotFoundError(SeederError): ...
class SeederDependencyError(SeederError): ...
class SeederExecutionError(SeederError): ...
class SeederFileError(SeederError): ...
class SeederBatchError(SeederError): ...
